splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/oscar/Pictures/Wallpapers/Waywallen/ciudad-cyberpunk.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/oscar/Pictures/Wallpapers/Waywallen/ciudad-cyberpunk.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/oscar/Pictures/Wallpapers/Waywallen/ciudad-pixelart.png
    fit_mode = cover
}
