hl.env("XCURSOR_THEME", "oreo_teal_cursors")
hl.env("XCURSOR_SIZE", "32")
hl.env("HYPRCURSOR_THEME", "oreo-teal-hyprcursor")
hl.env("HYPRCURSOR_SIZE", "32")

hl.config({
    autogenerated = false,
})

require("modules/input")
require("modules/appearance")
require("machines/linuxpc")
require("modules/autostart")
require("modules/binds")
require("modules/animations")
require("modules/rules")
-- require("modules/workspaces")
