hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "bibata-modern-ice-hyprcursor")
hl.env("HYPRCURSOR_SIZE", "24")

hl.config({
    autogenerated = false,
})

require("modules/input")
require("modules/appearance")
require("machines/linuxpc")
require("modules/autostart")
require("modules/binds")
require("modules/animations")
require("modules/rules")
require("modules/workspaces")
