--conf min de Hyprland

hl.config({
    autogenerated = false,

    input = {
        kb_layout = "latam",
        follow_mouse = 1,
        sensitivity = 0,
    },




--    general = {
--       border_size = 2,
--        col.active_border = "rgb(89b4fa)",
--        col.inactive_border = "rgb(4c566a)",
--    },

decoration = {
    rounding = 12,
    active_opacity = 1.0,
    inactive_opacity = 0.95,

    blur = {
        enabled = true,
        size = 8,
        passes = 3,
    },

    shadow = {
        enabled = true,
        range = 12,
        render_power = 3,
    },
},
})


hl.monitor({
    output = "DP-1",
    mode = "1920x1080@143.98",
    position = "0x0",
    scale = 1,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@180",
    position = "1920x0",
    scale = 1,
})

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60",
    position = "3840x0",
    scale = 1,
})






--abrir kitty

hl.bind(
	"SUPER + Q",
	hl.dsp.exec_cmd("kitty"),
	{ description = "Abrir Kitty" }
)


--cerrar ventana activa
hl.bind(
	"SUPER + C",
	hl.dsp.window.close(),
	{ description = "Cerrar ventana"}
)



--abrir rofi
hl.bind(
	"SUPER + R",
	hl.dsp.exec_cmd("rofi -show drun"),
	{ description = "Abrir Rofi" }
)


hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("lxpolkit")
    hl.exec_cmd("hyprsunset")
end)


-- Captura de pantalla


-- Seleccionar un área
hl.bind(
    "SUPER + SHIFT + S",
    hl.dsp.exec_cmd("hyprshot -m region --clipboard-only")
)

-- Capturar una ventana
hl.bind(
    "SUPER + SHIFT + W",
    hl.dsp.exec_cmd("hyprshot -m window --clipboard-only")
)

-- Capturar un monitor
hl.bind(
    "SUPER + SHIFT + A",
    hl.dsp.exec_cmd("hyprshot -m output --clipboard-only")
)


-- Abrir explorador
hl.bind(
    "SUPER + E",
    hl.dsp.exec_cmd("nemo"),
    { description = "Abrir Nemo" }
)

-- Workspaces: 
-- SUPER + número: ir al workspace
-- SUPER + SHIFT + número: mover la ventana al workspace

for i = 1, 9 do
    hl.bind(
        "SUPER + " .. i,
        hl.dsp.focus({ workspace = i }),
        { description = "Ir al workspace " .. i }
    )

    hl.bind(
        "SUPER + SHIFT + " .. i,
        hl.dsp.window.move({
            workspace = i,
            follow = true,
        }),
        { description = "Mover ventana al workspace " .. i }
    )
end