$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(8, 8, 8)
}

label {
    monitor =
    text = $TIME
    color = rgb(255, 255, 255)
    font_size = 90
    font_family = $font

    position = 0, 90
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 58
    outline_thickness = 2
    inner_color = rgb(30, 30, 46)
    outer_color = rgb(137, 180, 250)
    check_color = rgb(137, 180, 250)
    fail_color = rgb(243, 139, 168)
    font_color = rgb(205, 214, 244)
    font_family = $font
    fade_on_empty = false
    rounding = 12
    placeholder_text = <i>Contraseña</i>
    check_text = <i>Verificando...</i>
    fail_text = <i>$PAMFAIL</i>

    position = 0, -60
    halign = center
    valign = center
}
