hl.on("hyprland.start", function()
	hl.exec_cmd("~/.local/bin/waybar-multi")
	hl.exec_cmd("sleep 2; ~/.local/bin/waybar-hover >/tmp/waybar-hover.log 2>&1 &")
	hl.exec_cmd("lxpolkit")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd([[sleep 2; hyprctl dispatch 'hl.dsp.focus({ monitor = "HDMI-A-1" })'; snappy-switcher --daemon >/tmp/snappy-switcher.log 2>&1]])
	hl.dsp.exec_once("wl-paste --type text --watch cliphist store")
	hl.dsp.exec_once("wl-paste --type image --watch cliphist store")
end)